# Generated by Django 4.2.7 on 2024-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('free_msgs', models.IntegerField(default=1000)),
                ('stripe_customer_id', models.CharField(default='')),
                ('stripe_subscription_id', models.CharField(default='')),
                ('subscription_package', models.CharField(default='')),
                ('subscription_is_active', models.BooleanField(default=False)),
                ('subscription_is_cancelled', models.BooleanField(default=False)),
                ('messages_left', models.IntegerField(default=0)),
                ('current_usage', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
