# Generated by Django 4.2.6 on 2023-11-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authbackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_paid',
            new_name='subscription_is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='messages_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_package',
            field=models.CharField(default=''),
        ),
    ]
