# Generated by Django 4.2.6 on 2023-11-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authbackend', '0002_rename_is_paid_user_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
