# Generated by Django 4.2.4 on 2023-09-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='character_key',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.charactercard'),
            preserve_default=False,
        ),
    ]
