# Generated by Django 4.2.7 on 2023-12-12 09:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_character_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='msg_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=4), size=None),
        ),
    ]
